services:
#####micro-service clients
  targetServiceClient:
    class: FastMicroKernel\Components\ServiceClientsFactory
    factory: ['FastMicroKernel\Components\ServiceClientsFactory', 'getServiceClient']
    arguments:
      - '@=constant("TARGET_SERVICE_CLIENT_TRANSPORT")'
      - /target

#####micro-service request builder
  serviceRequestBuilder:
    class: FastMicroKernel\Components\ServiceRequestBuilder

#####monolith service
  service:
    class: Monolith\Components\Service
    arguments:
      - '@targetServiceClient'
      - '@contentServiceClient'
      - '@serviceRequestBuilder'

#####middleware
  testMiddlware:
    class: FastMicroKernel\Components\Test
  testDelegate:
    class: FastMicroKernel\Components\TestDelegate
